GET http://localhost:3001/api/beers

###

GET http://localhost:3001/api/beers

###

GET http://localhost:3001/api/beers/2022-10-21

###

POST http://localhost:3001/api/beers
Content-Type: application/json

{
  "content": {"nah": 1, "alright": 12, "yeah": 2},
  "date": "2022-10-16"
}

###

PUT http://localhost:3001/api/beers/2022-10-17
Content-Type: application/json

{
  "content": {"nah": 1, "alright": 1, "yeah": 3},
  "date": "2022-10-17"
}
