GET http://localhost:3001/api/beers

###

GET http://localhost:3001/api/beers

###

GET http://localhost:3001/api/beers/2022-10-21

###

POST http://localhost:3001/api/beers
Content-Type: application/json

{
  "content": {"nah": 19, "alright": 2, "yeah": 37},
  "date": "2022-10-21"
}

###

PUT http://localhost:3001/api/beers/2022-10-21
Content-Type: application/json

{
  "content": {"nah": 21, "alright": 4, "yeah": 38},
  "date": "2022-10-21"
}
